;;; Cask -- Scame cask file

;; Copyright (C) 2014  Nicolas Lamirault <nicolas.lamirault@gmail.com>

;; This program is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;; Commentary:

;; This is Scame dependencies
;; Install cask (https://github.com/cask/cask) and run in your ~/.emacs.d/
;;  $ `cask install'

;;; Code:

(source "melpa" "http://melpa.milkbox.net/packages/")
(source "gnu" "http://elpa.gnu.org/packages/")
;;(source "marmalade" "http://marmalade-repo.org/packages/")
(source "org" "http://orgmode.org/elpa/")


;; Common libraries
(depends-on "s")
(depends-on "f")
(depends-on "epl")
(depends-on "dash")
(depends-on "helm")

;; Scame tools
(depends-on "cask")
(depends-on "pallet")
(depends-on "use-package")
(depends-on "paradox")

(depends-on "benchmark-init")

;; Completion
(depends-on "company")
(depends-on "helm-company")
(depends-on "auto-complete")

;; Project
(depends-on "projectile")
(depends-on "helm-projectile")
(depends-on "persp-projectile")
(depends-on "find-file-in-project")
(depends-on "sr-speedbar")
(depends-on "nav")
(depends-on "neotree")
(depends-on "pt")
(depends-on "fill-column-indicator")

(depends-on "imenu-anywhere")
(depends-on "dired-imenu")

(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "flycheck-color-mode-line")
(depends-on "helm-flycheck")
;;(depends-on "flycheck-google-cpplint")


;; Common Lisp
;; (depends-on "slime")
;; (depends-on "slime-company")
(depends-on "sly")

;; Emacs Lisp
(depends-on "elisp-slime-nav")
(depends-on "erefactor")

;; Go lang
(depends-on "go-mode")
(depends-on "go-play")
;;(depends-on "go-autocomplete")
(depends-on "company-go")
(depends-on "go-eldoc")
(depends-on "helm-go-package")
;;(depends-on "helm-godoc")
;;(depends-on "flymake-go")
(depends-on "gotest")
(depends-on "go-direx")
(depends-on "go-projectile")
(depends-on "go-errcheck")
(depends-on "golint")

;; Python
;;(depends-on "python-mode")
(depends-on "jedi")
(depends-on "elpy")
(depends-on "tox")
(depends-on "virtualenvwrapper")
(depends-on "pyvenv")
;;(depends-on "flymake-python-pyflakes")
(depends-on "anaconda-mode")
(depends-on "company-anaconda")
;;(depends-on "company-inf-python")
(depends-on "jedi-direx")
(depends-on "sphinx-doc")
(depends-on "helm-pydoc")
(depends-on "pip-requirements")

;; Ruby

(depends-on "ruby-mode")
(depends-on "rvm")
(depends-on "rhtml-mode")
(depends-on "ruby-tools")
(depends-on "inf-ruby")
(depends-on "company-inf-ruby")
(depends-on "ruby-test-mode")

;; Erlang
(depends-on "erlang")

;; Scheme
(depends-on "geiser")

;; Clojure
(depends-on "cider")
(depends-on "clj-refactor")

;; Haskell
(depends-on "haskell-mode")
(depends-on "flycheck-haskell")
(depends-on "ghci-completion")

;; OCaml
(depends-on "tuareg")
(depends-on "merlin")

;; Web
(depends-on "web-mode")

;; Php
(depends-on "php-mode")
(depends-on "emacsagist")
(depends-on "phpunit")
;;(depends-on "flymake-php")

;; Perl
(depends-on "cperl-mode")
;;(depends-on "plsense-direx")
(depends-on "helm-perldoc")

;; Javascript
(depends-on "js3-mode")
(depends-on "tern")
(depends-on "company-tern")

;; C/C++
(depends-on "google-c-style")
(depends-on "c-eldoc")
;; (depends-on "auto-complete-c-headers")
(depends-on "company-c-headers")

;; Rust
(depends-on "rust-mode")

;; Markup languages
(depends-on "markdown-mode")
(depends-on "yaml-mode")
(depends-on "fountain-mode")
(depends-on "toml-mode")

;; Other development mode

(depends-on "fixmee")

;; TDD
(depends-on "cerbere")

;; Cloud
(depends-on "dockerfile-mode")
(depends-on "vagrant")
(depends-on "puppet-mode")
(depends-on "ansible")

;; File handling
(depends-on "launch")

;; Git and friends
(depends-on "magit")
(depends-on "magit-gerrit")
(depends-on "git-commit-mode")
(depends-on "gitconfig-mode")
(depends-on "gitignore-mode")
(depends-on "gitattributes-mode")
(depends-on "git-rebase-mode")
(depends-on "gist")
(depends-on "git-gutter+")
(depends-on "git-timemachine")
(depends-on "helm-open-github")

;; Utilities
(depends-on "pkg-info")
(depends-on "perspective")
(depends-on "project-persist")
(depends-on "helm-project-persist")
(depends-on "multi-term")
;;(depends-on "project-explorer")
(depends-on "lice")
(depends-on "commander")
(depends-on "smex")
(depends-on "emamux")
(depends-on "init-loader")
(depends-on "fabric")
(depends-on "prodigy")
(depends-on "helm-mode-manager")
(depends-on "ag")
(depends-on "json-reformat")
;;(depends-on "sos")
(depends-on "ace-jump-mode")
(depends-on "helm-proc")
(depends-on "helm-descbinds")
;;(depends-on "helm-delicious")

;; Search
(depends-on "helm-ack")
(depends-on "helm-ag")
(depends-on "swoop")
(depends-on "helm-swoop")

;; Mail
;;(depends-on "mu4e")
(depends-on "w3m")
(depends-on "offlineimap")

;; IM
(depends-on "jabber")

;; IRC
(depends-on "circe")
(depends-on "rcirc-groups")
(depends-on "rcirc-alertify")
(depends-on "rcirc-notify")

;; Organisation
(depends-on "org")
(depends-on "org-agenda-property")
(depends-on "org-caldav")
(depends-on "org-journal")
(depends-on "orgbox")
;;(depends-on "google-weather")
(depends-on "weather-metno")
;;(depends-on "org-jira")
;;(depends-on "org-ehtml")
(depends-on "calfw")
;;(depends-on "orgbox")

(depends-on "htmlize")
;;(depends-on "web-server")

;; Security
;; FIXME: website unavailable
;;(depends-on "password-store")

;; Specs
(depends-on "know-your-http-well")

;; UI
(depends-on "smart-mode-line")
(depends-on "diminish")
(depends-on "powerline")
(depends-on "popwin")
;;(depends-on "golden-ratio")

;; Dired and friends
(depends-on "direx")
;;(depends-on "dired-k")
(depends-on "dired-filter")
(depends-on "dired-open")
(depends-on "dired-rainbow")
(depends-on "dired-subtree")

;; Sysadmin
(depends-on "nginx-mode")
(depends-on "syslog-mode")
(depends-on "apache-mode")

;; Gnus
(depends-on "gnus-x-gm-raw")
;;(depends-on "google-contacts")
(depends-on "bbdb")
(depends-on "bbdb-")
(depends-on "bbdb-ext")
(depends-on "bbdb-csv-import")

;; Misc
(depends-on "guide-key")

;; Themes
(depends-on "moe-theme")
(depends-on "zenburn-theme")
(depends-on "color-theme-sanityinc-tomorrow")
(depends-on "noctilux-theme")
(depends-on "afternoon-theme")
(depends-on "ample-theme")
(depends-on "subatomic-theme")
(depends-on "monokai-theme")


;; Development
(development
 (depends-on "ctable")
 (depends-on "request")
 (depends-on "pkg-info")
 (depends-on "commander")
 (depends-on "ert")
 (depends-on "el-mock")
 (depends-on "ert-runner"))

;;; Cask ends here.
