;;; Cask -- Scame cask file

;; Copyright (C) 2014  Nicolas Lamirault <nicolas.lamirault@gmail.com>

;; This program is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;; Commentary:

;;; Code:

(source "melpa" "http://melpa.milkbox.net/packages/")
(source "gnu" "http://elpa.gnu.org/packages/")
(source "marmalade" "http://marmalade-repo.org/packages/")


;; Common libraries
(depends-on "s")
(depends-on "f")
(depends-on "epl")
(depends-on "dash")

;; Scame tools
(depends-on "cask")
(depends-on "pallet")
(depends-on "use-package")
(depends-on "paradox")

(depends-on "benchmark-init")

(depends-on "auto-complete")
(depends-on "company")
(depends-on "helm-company")

(depends-on "sr-speedbar")
(depends-on "nav")

(depends-on "imenu-anywhere")
(depends-on "dired-imenu")

(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "flycheck-color-mode-line")
;;(depends-on "flycheck-google-cpplint")

;; Project
(depends-on "projectile")
(depends-on "helm-projectile")
(depends-on "persp-projectile")

;; Common Lisp
(depends-on "slime")
(depends-on "slime-company")

;; Emacs Lisp
(depends-on "elisp-slime-nav")
(depends-on "erefactor")

;; Go lang
(depends-on "go-mode")
(depends-on "go-play")
;;(depends-on "go-autocomplete")
(depends-on "company-go")
(depends-on "go-eldoc")
;;(depends-on "flymake-go")
(depends-on "gotest")
(depends-on "go-direx")
(depends-on "go-projectile")

;; Python
(depends-on "python-mode")
(depends-on "jedi")
(depends-on "elpy")
(depends-on "tox")
(depends-on "virtualenvwrapper")
(depends-on "pyvenv")
;;(depends-on "flymake-python-pyflakes")
(depends-on "anaconda-mode")
(depends-on "jedi-direx")
(depends-on "sphinx-doc")

;; Ruby

(depends-on "rvm")
(depends-on "rhtml-mode")
(depends-on "ruby-tools")
(depends-on "inf-ruby")
(depends-on "ruby-mode")
(depends-on "company-inf-ruby")

;; Erlang
(depends-on "erlang")

;; Scheme
(depends-on "geiser")

;; Clojure
(depends-on "cider")
(depends-on "company-cider")
(depends-on "clj-refactor")

;; Haskell
(depends-on "haskell-mode")
(depends-on "flycheck-haskell")
(depends-on "ghci-completion")

;; OCaml
(depends-on "tuareg")
(depends-on "merlin")

;; Web
(depends-on "web-mode")

;; Php
(depends-on "php-mode")
(depends-on "emacsagist")
(depends-on "phpunit")
;;(depends-on "flymake-php")

;; Perl
(depends-on "plsense-direx")

;; Javascript
(depends-on "company-tern")

;; C/C++
(depends-on "google-c-style")
(depends-on "c-eldoc")
(depends-on "auto-complete-c-headers")

;; Markup languages
(depends-on "markdown-mode")
(depends-on "yaml-mode")

;; Other development mode

;; TDD
(depends-on "cerbere")

;; Cloud
(depends-on "dockerfile-mode")
(depends-on "vagrant")
(depends-on "puppet-mode")

;; File handling
(depends-on "launch")

;; Git and friends
(depends-on "magit")
(depends-on "git-commit-mode")
(depends-on "gitconfig-mode")
(depends-on "gitignore-mode")
(depends-on "gitattributes-mode")
(depends-on "git-rebase-mode")
(depends-on "gist")

;; Utilities
(depends-on "pkg-info")
(depends-on "helm")
(depends-on "perspective")
(depends-on "project-persist")
(depends-on "helm-project-persist")
(depends-on "multi-term")
(depends-on "project-explorer")
(depends-on "lice")
(depends-on "commander")
(depends-on "smex")
(depends-on "swoop")
(depends-on "emamux")
(depends-on "init-loader")
(depends-on "fabric")
(depends-on "prodigy")
(depends-on "helm-mode-manager")
(depends-on "ag")
(depends-on "json-reformat")
(depends-on "sos")
(depends-on "ace-jump-mode")

;; Mail
;;(depends-on "mu4e")
;;(depends-on "w3m")
;;(depends-on "offlineimap")

;; Organisation
(depends-on "org")
(depends-on "google-weather")
(depends-on "weather-metno")
;;(depends-on "org-jira")
(depends-on "org-ehtml")
(depends-on "calfw")
(depends-on "orgbox")

(depends-on "htmlize")
(depends-on "web-server")

;; Security
(depends-on "password-store")

;; UI
(depends-on "smart-mode-line")
(depends-on "diminish")
(depends-on "powerline")
(depends-on "popwin")
;;(depends-on "golden-ratio")

;; Dired and friends
(depends-on "direx")
;;(depends-on "dired-k")
(depends-on "dired-filter")
(depends-on "dired-open")
(depends-on "dired-rainbow")
(depends-on "dired-subtree")

;; Gnus
(depends-on "google-contacts")


;; Themes
(depends-on "moe-theme")
(depends-on "zenburn-theme")
(depends-on "color-theme-sanityinc-tomorrow")
(depends-on "noctilux-theme")
(depends-on "afternoon-theme")
(depends-on "ample-theme")
(depends-on "subatomic-theme")
(depends-on "monokai-theme")


;; Development
(development
 (depends-on "ctable")
 (depends-on "request")
 (depends-on "pkg-info")
 (depends-on "commander")
 (depends-on "ert")
 (depends-on "ert-runner"))
